spring:
  datasource:
    username: jplausi-prod
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
    url: jdbc:postgresql://localhost:5433/companies-prod
    password: uirhknñowejñljsdui
